### PR TITLE
add AES-128-ECB support

### PR DESCRIPTION
**Pull request by shrkw**
Hi,

I wanted to use AES- 128-ECB as encryption algorithm. Ah yes, I know it is not recommended algorithm at all, but it is default encryption algorithm on MySQL 5.7 and AWS aurora MySQL does not allow block_encryption_mode parameter. So I had to do it.

### CODE REVIEW

**Comment by shrkw** [comment]
Ah I noticed when nil or zero length value is provided, it raise 'output error: #<ArgumentError: data must not be empty>'. I'll add testcases and fix it.

**Comment by shrkw** [comment]
hmm, it seems CI failed this job https://travis-ci.com/github/alpaca-tc/active_record_encryption/jobs/396857882 but it is not point I changed last commit. Do you have any idea to fix this?

**Comment by shrkw** [comment]
re-run may fix it.

**Comment by alpaca-tc** [comment]
@shrkw Thank you for your PR :)

hmmm... 
I don't want to support AES-ECB because it is dangerous algorithm as you know. How about using custom encryptor like the following code instead of?

```
class YourEncryptor < ActiveRecordEncryption::Encryptor::Base
  def initialize(key:)
    @key = key
  end

  def encrypt(value)
    # An encrypt method that returns the encrypted string
  end

  def decrypt(value)
    # A decrypt method that returns the plaintext
  end
end

ActiveRecordEncryption.default_encryption = {
  encryptor: YourEncryptor,
  key: ENV['ENCRYPTION_KEY']
}
```

**Comment by shrkw** [comment]
Thank you for your reply, yeah I can understand your decision.

One question, I added my own encryptor (e.g. app/models/my_encryptor.rb), and load it from initializer (config/initializers/active_record_encryption.rb). So when I execute `rails console`, then it happens `uninitialized constant ActiveRecordEncryption::Encryptor (NameError)`.

Where should those are stored?

```
        67: from bin/rails:4:in `<main>'
        66: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        65: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        64: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        63: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        62: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        61: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<main>'
        60: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/command.rb:46:in `invoke'
        59: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/command/base.rb:69:in `perform'
        58: from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        57: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        56: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        55: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/commands/console/console_command.rb:101:in `perform'
        54: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        53: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/command/actions.rb:28:in `require_environment!'
        52: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/application.rb:339:in `require_environment!'
        51: from /usr/local/bundle/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
        50: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        49: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        48: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        47: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        46: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        45: from /workspace/config/environment.rb:7:in `<main>'
        44: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/application.rb:363:in `initialize!'
        43: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/initializable.rb:60:in `run_initializers'
        42: from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        41: from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        40: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        39: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
        38: from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
        37: from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        36: from /usr/local/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        35: from /usr/local/lib/ruby/2.6.0/tsort.rb:415:in `call'
        34: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/initializable.rb:50:in `tsort_each_child'
        33: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/initializable.rb:50:in `each'
        32: from /usr/local/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        31: from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        30: from /usr/local/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        29: from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        28: from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        27: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        26: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `run'
        25: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `instance_exec'
        24: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/engine.rb:624:in `block in <class:Engine>'
        23: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/engine.rb:624:in `each'
        22: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
        21: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/engine.rb:665:in `load_config_initializer'
        20: from /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:182:in `instrument'
        19: from /usr/local/bundle/gems/railties-6.0.3.3/lib/rails/engine.rb:666:in `block in load_config_initializer'
        18: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        17: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        16: from /workspace/config/initializers/active_record_encryption.rb:14:in `<main>'
        15: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
        14: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
        13: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
        12: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
        11: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
        10: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
         9: from /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
         8: from /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
         7: from /usr/local/bundle/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
         6: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
         5: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
         4: from /workspace/app/lib/your_encryptor.rb:5:in `<main>'
         3: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
         2: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
         1: from /usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
/usr/local/bundle/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant': uninitialized constant ActiveRecordEncryption::Encryptor (NameError)
```

**Comment by alpaca-tc** [comment]
@shrkw Please require activerecord before initializer because AREncrtion is loaded by `ActiveSupport.on_load`.

**Comment by shrkw** [comment]
Thank you!
Following works fine!

config/initializers/active_record_encryption.rb
```
require_relative "../../app/models/my_encryptor"

ActiveRecordEncryption.default_encryption = {
  encryptor: MyEncryptor,
  key: 'foo'
}
```

app/models/my_encryptor.rb
```
require 'active_record_encryption/encryptor'

class MyEncryptor < ActiveRecordEncryption::Encryptor::Base
  def initialize(key:)
    @key = key
  end

  def encrypt(value)
    value
  end

  def decrypt(value)
    value
  end
end
```

**Pull request closed without merging**
